# Generated by Django 2.0.3 on 2018-03-20 23:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_product', models.CharField(max_length=4)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_urls', models.TextField(null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(max_length=64)),
                ('available_destinations', models.CharField(max_length=64)),
                ('delivery_time', models.CharField(max_length=64)),
                ('delivery_size', models.CharField(max_length=64)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('e_mail', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=15)),
                ('company', models.CharField(default=None, max_length=64)),
                ('country', models.CharField(default=None, max_length=64)),
                ('city', models.CharField(default=None, max_length=64)),
                ('postal_code', models.CharField(default=None, max_length=64)),
                ('address1', models.CharField(default=None, max_length=64)),
                ('address2', models.CharField(default=None, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='products',
            field=models.ManyToManyField(related_name='photo', to='online_shop.Product'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders_product', to='online_shop.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_options',
            field=models.ManyToManyField(related_name='orders_shipping_option', to='online_shop.ShippingOption'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_user', to='online_shop.User'),
        ),
    ]
