# Generated by Django 2.0.2 on 2018-03-05 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quentity',
        ),
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image_urls',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='online_shop.Products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
