# Generated by Django 2.0.3 on 2018-03-22 21:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_shop', '0003_auto_20180322_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser',
            new_name='Profile',
        ),
    ]
