# Generated by Django 2.0.3 on 2018-03-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_auto_20180322_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
