# Generated by Django 2.0.2 on 2018-03-05 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0006_auto_20180305_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_product', to='online_shop.Products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_user', to='online_shop.Users'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='online_shop.Products'),
        ),
    ]
