# Generated by Django 2.0.2 on 2018-03-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0008_auto_20180305_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='products',
            field=models.ManyToManyField(related_name='photo', to='online_shop.Products'),
        ),
    ]
