# Generated by Django 2.0.2 on 2018-03-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0009_auto_20180305_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
