# Generated by Django 2.0.3 on 2018-03-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0012_auto_20180319_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders_product', to='online_shop.Product'),
        ),
    ]
