# Generated by Django 2.0.4 on 2018-05-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='quantity_product',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(2, 'Confirmed / Rejected'), (5, 'Delivered'), (1, 'Waiting for confirmation'), (3, 'Processing'), (4, 'Sent')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default='iXBxtycfFpfgUgm4d9pGLL', editable=False, max_length=25),
        ),
    ]
