# Generated by Django 2.0.4 on 2018-05-13 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180513_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(2, 'Confirmed / Rejected'), (5, 'Delivered'), (1, 'Waiting for confirmation'), (4, 'Sent'), (3, 'Processing')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default='srWZfP89kTezjekPbkvQgX', editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sale', to='shop.Order'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale', to='shop.Product'),
        ),
    ]
