# Generated by Django 2.0.4 on 2018-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180513_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Waiting for confirmation'), (2, 'Confirmed / Rejected'), (3, 'Processing'), (4, 'Sent'), (5, 'Delivered')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(editable=False, max_length=25),
        ),
    ]
