# Generated by Django 2.0.4 on 2018-04-28 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180427_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(3, 'Quality check'), (1, 'Confirmed order'), (5, 'Product delivered'), (4, 'Product dispatched'), (0, 'Waiting for confirmation'), (2, 'Processing order')], default=0, max_length=30),
        ),
    ]
